```{r include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE)
library(tidyverse)
library(knitr)
library(forcats)
library(httr)
library(xml2)
library(purrr)
library(leaflet)
library(sp)
library(stringr)
```

# MEP data

## Official MEP data

- [Members of the European Parliament (MEPs)](https://data.europa.eu/euodp/en/data/dataset/members-of-the-european-parliament)
- [Full list of MEPs elected in 2014 [XML]](http://www.europarl.europa.eu/meps/en/xml.html?query=full&filter=all)

Data frame: 

```{r}

r <- GET('http://www.europarl.europa.eu/meps/en/xml.html?query=full&filter=all')

xmldoc <- content(r, 'parse')

# adapted from https://github.com/jennybc/manipulate-xml-with-purrr-dplyr-tidyr

rows <- xmldoc %>% xml_find_all('//mep') %>% map(~ xml_find_all(.x,'./*'))
rows_df <- data_frame(row = seq_along(rows), nodeset = rows)

cells_df <- rows_df %>%
  mutate(col_name_raw = nodeset %>% map(~ xml_name(.)),
         cell_text = nodeset %>% map(~ xml_text(.)),
         i = nodeset %>% map(~ seq_along(.))) %>%
  select(row, i, col_name_raw, cell_text) %>%
  unnest()

df <- cells_df %>% 
      select(-i) %>% 
      spread(col_name_raw, cell_text) %>% 
      select(-row) %>%
      mutate(id=as.integer(id))

df

write_csv(df, '../docs/meps.csv')
```

- [CSV](meps.csv)

## MEPs in Wikidata

- [Wikidata Query](http://tinyurl.com/khdg6k3)

```{r}

endpoint <- 'https://query.wikidata.org/sparql'

query <- 
'
SELECT ?mep ?mepLabel ?mepId ?mepImage ?mepCityBorn ?mepCityBornLabel ?cityCoordinates
WHERE
{
  ?mep wdt:P1186 ?mepId.
    OPTIONAL {
      ?mep wdt:P18 ?mepImage .
      ?mep wdt:P19 ?mepCityBorn .
      ?mepCityBorn wdt:P625 ?cityCoordinates . 
    }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
'

query_r <- GET(endpoint, query = list(query = query), add_headers(Accept = 'text/csv'))
df_wikidata <- content(query_r, 'parse')

df_wikidata

```

# Mapping Wikidata MEPs

```{r}

# todo: still duplicates from different coordinates for same place, multiple origin cities... 
wikidata_add <- df_wikidata %>% select(mepId, mepCityBornLabel, cityCoordinates) %>% unique()

df_joined <- df %>% left_join(wikidata_add, by=c('id'='mepId'))

mapdata <- df_joined %>%
            mutate(cityCoordinates=str_replace(cityCoordinates,'Point\\(', '')) %>%
            mutate(cityCoordinates=str_replace(cityCoordinates,'\\)', '')) %>%
            separate(cityCoordinates, c('longitude', 'latitude'), sep=' ') %>%
            mutate(latitude=as.numeric(latitude), longitude=as.numeric(longitude)) %>%
            filter(!is.na(latitude), !is.na(longitude))

pal <- colorFactor(
        c(
          'blue',
          'red',
          'green',
          'white',
          'brown',
          'pink',
          'yellow',
          'cyan',
          'magenta'
        ), 
        domain = 
        df$politicalGroup %>% unique()
        )

m <- leaflet(data=mapdata) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addCircleMarkers(
    #radius = ~ifelse(type == "ship", 6, 10),
    color = ~pal(politicalGroup),
    stroke = FALSE, fillOpacity = 0.5,
    label = ~paste(politicalGroup, '\n', fullName)
  )


  #addAwesomeMarkers(~longitude, ~latitude, icons = icons, label = ~mepLabel)

m  # Print the map

```



